### PR TITLE
Feature/unit testing

### PR DESCRIPTION
**Pull request by acrinklaw**
Adds unit testing and splits out main

### CODE REVIEW

**Comment by raphaeltrevizani** [comment]
Thank you so much for creating this, @acrinklaw, and nice job on commenting the code. I tested the tcrmatch binary and it still works fine, but the test binary did not compile. Can you check these before I can proceed with merging? I attached the error log I got from the Makefile.
[errors.log](https://github.com/IEDB/TCRMatch/files/11327206/errors.log)

**Comment by acrinklaw** [comment]
@raphaeltrevizani no problem, happy to help. Also this is because of adding the c++11 standard parameter to the makefile, I think catch2 only supports >14

**Comment by raphaeltrevizani** [comment]
You're right, @acrinklaw. I can confirm that compiling with 
`g++ -fopenmp -O3 -g  -o test tests/test.cpp tests/catch_amalgamated.cpp`
solves the issue. Modifying the Makefile line should suffice then. Thanks!

**Review by raphaeltrevizani — APPROVED** [review]

**Comment by raphaeltrevizani** [comment]
Merged.

**Pull request closed without merging**
